SELECT BOARD.TITLE,
    BOARD.BOARD_ID,
    REPLY.REPLY_ID,
    REPLY.WRITER_ID,
    REPLY.CONTENTS,
    date_format(REPLY.CREATED_DATE,"%Y-%m-%d") AS DATE
FROM USED_GOODS_BOARD AS BOARD, USED_GOODS_REPLY AS REPLY
    
WHERE BOARD.BOARD_ID = REPLY.BOARD_ID AND
date_format(BOARD.CREATED_DATE, "%Y%m") = 202210

ORDER BY REPLY.CREATED_DATE, BOARD.TITLE
